### ISSUE TITLE
Difference in time stamps

### ISSUE THREAD

**Issue by AndreasAZiegler** [ros-event-camera/event_camera_py#1]
I'm using the following code to get the event data as a `csv` file from a recorded `bag` file. I'm a bit confused about the time stamps. With `rosrun rqt_bag rqt_bag` the bag starts at `1668442732.027111530` whereas the first "decoded" timestamp is `36418184`. Where does this difference come from?

```
import rosbag
from event_array_py import Decoder

topic = '/event_camera/events'
bag = rosbag.Bag('evk1_events_run_0.bag')
output_file = 'evk1_events_run_0.csv'
decoder = Decoder()

for topic, msg, t in bag.read_messages(topics=topic):
    decoder.decode_bytes(msg.encoding, msg.width, msg.height,
	                     msg.time_base, msg.events)
    cd_events = decoder.get_cd_events()
    print(cd_events)
    trig_events = decoder.get_ext_trig_events()
    print(trig_events)

    with open(output_file, 'w') as csv_file:
        for event in cd_events:
            x, y, p, t = event[0], event[1], event[2], event[3]
            csv_file.write("%d,%d,%d,%d\n" % (x, y, p, t))
```

**Comment by berndpfrommer** [comment]
When it comes to bags there are 3 time stamps:
1) The time the data was recorded in the bag. That's "t" in your code above.
2) The time the driver got the message. That's buried in msg.header.stamp and is definitely preferred over 1)
3) The sensor time. That one is buried in the binary message content and must be recovered by decoding. That time stamp rolls over about every 16 seconds. The decoder keeps track of the rollover so you will not immediately notice it. However it also means that you will get different time stamps depending on where you start decoding in the bag! If you want to see how the sausage is made, have a look at the sample EVT3 decoder: https://docs.prophesee.ai/stable/samples/standalone/evt3_decoder.html
One nasty feature of the time stamps is that they can have bit errors, and that can generate false rollovers. The decoder tries to guard against that, but if you see jumps of about 16s in the time stamps, you know where they come from.

If you use a synced setup you will need to use sensor time 3) to get the best correlation because that eliminates any differences due to the driver getting packets from different sources. The time stamps in the raw file should agree (if your sync actually works). But again, you will have to start decoding the two streams at roughly the same time, and if you are unlucky and  one of the streams has just rolled over, your time stamps could be shifted by the magical 16.x seconds.

Now why use ROS at all to collect sensor data? If you want to correlate with any other sensor (like IMU), you can compute the average offset between the message header  time stamps and the decoded sensor time stamps, and then "promote" your sensor time to ROS time. I had a solution for that in the driver at some point when the driver was still doing the decoding and publishing the decoded events. Now that it publishes the raw messages, that alignment between ROS and sensor time must be done during downstream processing.

**Comment by berndpfrommer** [comment]
Oh, forgot to mention: when I try to convert the bag to raw, then use the metavision SDK to play back the raw file with an iterator, I get yet another sensor time stamp that I cannot reproduce with my decoder. It seemed to have a fixed shift to what my decoder gives. The documentation for the SDK is fairly nebulous when it comes to the absolute value of their time stamps.

**Comment by AndreasAZiegler** [comment]
Thanks for your thorough reply. I'm using a setup where I record some data with an existing ROS setup. The data from this existing setup is saved in a text file (not ROS bags) and stores the ROS time stamps. My intention was to use the ROS time stamps to synchronize the data from this text files with the ros/raw file containing the events.
I'm currently only recording the events from one event camera. From the information you provided, it seems option 2) is the best.

**Comment by AndreasAZiegler** [comment]
One more question. In case I want to use the time stamps 3), how do I get them from the decoder? Do you have some example code for this?

**Comment by berndpfrommer** [comment]
Apologies for the edit, my first answer was wrong.
The sensor time stamps are what you get from the decoder. Those are the time stamps you were wondering about in your original post.

**Comment by AndreasAZiegler** [comment]
Okay, so to clarify: If I
* use `t = msg.header.stamp.to_nsec() / (10**6)`, I will get the time stamps when the driver got the message
* use `t = event[3]`, I will get the time stamps from the decoder (which are the time stamps from the EB camera with some strange 16.x seconds issue in some cases

Is my understanding right?

**Comment by berndpfrommer** [comment]
Yes, this is correct.

**Comment by berndpfrommer** [comment]
I think we are done with this issue :)
